### PR TITLE
Update to PowerShell 7.0(.1) on Ubuntu 18.04

### PR DESCRIPTION
**Pull request by alagoutte**

### CODE REVIEW

**Comment by alagoutte** [comment]
Hi,

Any news about this PR (and other PR ?)

also may be make like super-linter, a docker image ? (and avoid to rebuild image before each build ?)

**Comment by devblackops** [comment]
Thanks for all the updates @alagoutte. Sorry I've been neglecting these. There is an existing docker image at https://hub.docker.com/r/devblackops/github-action-psscriptanalyzer. When I merge these, I'll cut a new release.

Thanks again for all the fixes!

**Comment by devblackops** [comment]
Docker image 2.2.0 released. https://hub.docker.com/r/devblackops/github-action-psscriptanalyzer/tags

**Comment by alagoutte** [comment]
> Docker image 2.2.0 released. https://hub.docker.com/r/devblackops/github-action-psscriptanalyzer/tags

Thanks ! i will try

**Pull request merged**
